language: node_js
node_js:
  - 0.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g testacular
  - ./scripts/web-server.js > /dev/null &
  - sleep 1 # give server time to start

script:
  - testacular start config/testacular.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - testacular start config/testacular-e2e.conf.js --reporters=dots --browsers=Firefox

env:
  global:
    - secure: "gi++FGOhcmlLoyRg3K31k+WMNAsTCDsyfXJBcwvzfMxusTz4OriXoqTX6mck\nWok0YL3+LcV5aibB8PKd91BkffBbmFeHIvQN212HnWrtN2i3oJf5lvGJ+B8S\nJzKD/G2r2QoBy6tsD7I4+11zkmhpGt/IYZb1j51ppkRXcjrPiGs="

after_script:
  - git clone --quiet https://$GITHUB_TOKEN:x-oauth-basic@github.com/jedimdan/awesome-start.git awesome-start
  - ls
  - cd awesome-start
  - git checkout gh-pages
  - git merge master
  - git push origin master

