branches:
  only:
    - gh-pages

language: node_js
node_js:
  - 0.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g karma
  - ./scripts/web-server.js > /dev/null &
  - sleep 1 # give server time to start

script:
  - karma start config/testacular-e2e.conf.js --reporters=dots --browsers=Firefox

env:
  global:
    - secure: "LE+E71u2AhDdXNkTzU2wxxLJ/ScfRiuXVdtIxYlOrLbl8HtBPCZnnxFnKCuw\nqe7I8++Tp+/jY7e3Tt1wxllMx8qJDLPOlAMWSZ2W7vf3BpQuhX/r1hlVQbaA\nMcVkmnirTfJrxnUMqZmOSPqWFBjk179x4VIpa+Ze0v5hUBhqeVI="

after_success:
- cd ..
- ls
- wget http://googleappengine.googlecode.com/files/google_appengine_1.7.4.zip -nv
- unzip -q google_appengine_1.7.4.zip
- google_appengine/appcfg.py --oauth2_refresh_token=$GAE_TOKEN update awesome-start